main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.HomeView.as_view(), name="home"),
    path('service-detail/<int:pk>/', views.ServiceDetailView.as_view(), name="service_detail"),
    path('about-us/', views.AboutUsView.as_view(), name="about_us"),
    path('our-service/', views.ServicesView.as_view(), name="our_service"),
    path('contact-us/', views.ContactUsView.as_view(), name="contact_us"),
    path('team-member/', views.TeamMemberView.as_view(), name="team_member"),
]

savijo/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]


admin.site.site_header = 'Savijo Adminstration'
admin.site.site_title = 'Savijo Admin'

main/models.py
from django.db import models

class Service(models.Model):
    title = models.CharField(max_length=100)
    svg_icon = models.CharField(max_length=20)
    description_top_image = models.CharField(max_length=100, blank=True, null=True)
    description = models.TextField()
    active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        db_table = "service"
        ordering = ["-id"]

main/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import DetailView
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from .models import Service


class HomeView(View):
    template_name = "main/home.html"

    def get(self, request, *args, **kwargs):

        service_list = Service.objects.filter(active=True).order_by('id')
        
        context = {}
        context["title"] = "Home"
        context['first_four_service_list'] = service_list[:4]
        context['last_four_service_list'] = service_list[4:]
        return render(request, self.template_name, context)


class ServiceDetailView(DetailView):
    model = Service

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        service_list = Service.objects.filter(active=True).order_by('id')

        context['title'] = 'Service'
        context['service_list'] = service_list
        return context

    def get_object(self):
        return get_object_or_404(self.model, pk=self.kwargs['pk'], active=True)


class AboutUsView(View):
    template_name = "main/about_us.html"

    def get(self, request, *args, **kwargs):
        
        context = {}
        context["title"] = "About Us"
        return render(request, self.template_name, context)
    

class ServicesView(View):
    template_name = "main/services.html"

    def get(self, request, *args, **kwargs):

        service_list = Service.objects.filter(active=True).order_by('id')
        
        context = {}
        context["title"] = "Our Services"
        context['service_list'] = service_list
        return render(request, self.template_name, context)
    

class ContactUsView(View):
    template_name = "main/contact_us.html"

    def get(self, request, *args, **kwargs):
        
        context = {}
        context["title"] = "Contact Us"
        return render(request, self.template_name, context)
    

class TeamMemberView(View):
    template_name = "main/team_member.html"

    def get(self, request, *args, **kwargs):
        
        context = {}
        context["title"] = "Our Team Member"
        return render(request, self.template_name, context)

templates/include/footer.html
{% load static %}

<!-- JS
         ============================================ -->
<!-- jQuery JS -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- Popper JS -->
<script src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'js/bootstrap.min.js' %}"></script> 
<!-- jquery Waypoints JS -->
<script src="{% static 'js/jquery.waypoints.min.js' %}"></script>
<!-- jquery Appear JS -->
<script src="{% static 'js/jquery.appear.js' %}"></script>
<!-- Numinate JS -->
<script src="{% static 'js/numinate.min.js' %}"></script>
<!-- Swiper JS -->
<script src="{% static 'js/swiper.min.js' %}"></script>
<!-- Magnific JS -->
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<!-- Circle Progress JS -->
<script src="{% static 'js/circle-progress.js' %}"></script>  
<!-- Scripts JS -->
<script src="{% static 'js/scripts.js' %}"></script>        
<!-- Revolution JS -->
<script src="{% static 'revolution/rslider.js' %}"></script>
<script src="{% static 'revolution/rbtools.min.js' %}"></script>
<script src="{% static 'revolution/rs6.min.js' %}"></script> 
<script>(function(){var js = "window['__CF$cv$params']={r:'81ec2d39ffceb981',t:'MTY5ODc1ODIzMC40ODYwMDA='};_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='../cdn-cgi/challenge-platform/h/g/scripts/jsd/c359bc3d/main.js',document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script><script defer src="https://static.cloudflareinsights.com/beacon.min.js/v84a3a4012de94ce1a686ba8c167c359c1696973893317" integrity="sha512-euoFGowhlaLqXsPWQ48qSkBSCFs3DPRyiwVu3FjR96cMPx+Fr+gpWRhIafcHwqwCqWS42RZhIudOvEI+Ckf6MA==" data-cf-beacon='{"rayId":"81ec2d39ffceb981","version":"2023.10.0","r":1,"token":"125856bf84ab44059737e93b01aa0fef","b":1}' crossorigin="anonymous"></script>

templates/include/header.html
{% load static %}

<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>Savijo | {{title}}</title>
<meta name="robots" content="noindex, follow">
<meta name="description" content="">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'images/fevicon.png' %}">
<!-- CSS
    ============================================ -->
<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<!-- Fontawesome -->
<link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
<!-- Flaticon -->
<link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
<!-- Base Icons -->
<link rel="stylesheet" href="{% static 'css/pbminfotech-base-icons.css' %}"> 
<!-- Swiper -->
<link rel="stylesheet" href="{% static 'css/swiper.min.css' %}">
<!-- Magnific -->
<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}"> 
<!-- Shortcode CSS -->
<link rel="stylesheet" href="{% static 'css/shortcode.css' %}">
<!-- Base CSS -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
<!-- Style CSS -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Responsive CSS -->
<link rel="stylesheet" href="{% static 'css/responsive.css' %}">
<!-- REVOLUTION STYLE SHEETS -->
<link rel="stylesheet" type="text/css" href="{% static 'revolution/rs6.css' %}">

templates/include/image_slider.html
{% load static %}

<div class="pbmit-slider-area">
    <!-- START Slider Demo 3 REVOLUTION SLIDER 6.5.20 --><p class="rs-p-wp-fix"></p>
    <rs-module-wrap id="rev_slider_3_1_wrapper" data-alias="slider-demo-3" data-source="gallery" style="visibility:hidden;background:transparent;padding:0;margin:0px auto;margin-top:0;margin-bottom:0;">
        <rs-module id="rev_slider_3_1" data-version="6.5.20">
            <rs-slides>
                <rs-slide style="position: absolute;" data-key="rs-1" data-title="Slide" data-thumb="revolution/images/slider-1.jpg' %}" data-in="o:0;" data-out="a:false;">
                    <img src="{% static 'revolution/images/slider-1.jpg' %}" alt="" title="slider03-img1.jpg' %}" width="1920" height="815" class="rev-slidebg tp-rs-img" data-no-retina>
                    <rs-layer
                        id="slider-1-slide-1-layer-0"
                        data-type="text"
                        data-rsp_ch="on"
                        data-xy="xo:30px,24px,30px,30px;y:m;yo:-85px,-59px,-50px,-23px;"
                        data-text="w:normal;s:84,75,60,45;l:84,75,60,45;fw:500;"
                        data-frame_0="x:175%;o:1;"
                        data-frame_0_mask="u:t;x:-100%;"
                        data-frame_1="e:power3.out;st:1490;sp:1000;sR:1490;"
                        data-frame_1_mask="u:t;"
                        data-frame_999="o:0;st:w;sR:6510;"
                        style="z-index:10;font-family:'Teko';"
                    >Setting Global Standards<br>in Geology, Environment<br/> and Oil &amp; Gas Solutions
                    </rs-layer><!--

                    --><rs-layer
                        id="slider-1-slide-1-layer-1" 
                        data-type="text"
                        data-rsp_ch="on"
                        data-xy="xo:30px,24px,30px,18px;y:m;yo:-247px,-199px,-160px,-98px;"
                        data-text="w:normal;s:22,20,20,12;l:30,24,24,14;"
                        data-vbility="t,t,t,f"
                        data-frame_0="x:50,41,31,19;"
                        data-frame_1="st:1000;sp:1000;sR:1000;"
                        data-frame_999="o:0;st:w;sR:7000;"
                        style="z-index:9;font-family:'Yantramanav';"
                    >
                    Savijo Geo-Engineering: Your Trusted Experts
                    </rs-layer>
                    
                    <a id="slider-1-slide-1-layer-2" class="rs-layer rev-button rev-btn" href="contact-us" target="_self" data-type="button" data-rsp_ch="on" data-xy="xo:31px,24px,18px,11px;y:m;yo:116px,96px,22px,13px;" data-text="w:normal;s:18;l:60,55,50,45;ls:1px,1px,1px,0px;fw:300;" data-dim="minh:0px,none,none,none;" data-padding="t:4,5,3,4;r:50,42,40,35;l:50,42,40,35;" data-border="bor:0px,25px,0px,0px;" data-frame_0="x:-100%;" data-frame_0_mask="u:t;" data-frame_1="st:2660;sp:1000;sR:2660;" data-frame_1_mask="u:t;" data-frame_999="o:0;st:w;sR:5340;" data-frame_hover="bgc:#fc0012;bor:0px,25px,0px,0px;" style="z-index:13;background-color:#111010;font-family:'Teko';text-transform:uppercase;"><span>Get a quote</span> 
                    </a>
                    
                    <rs-layer
                        id="slider-1-slide-1-layer-6" 
                        data-type="shape"
                        data-rsp_ch="on"
                        data-xy="xo:197px,175px,181px,111px;y:m;yo:-247px,-199px,-160px,-98px;"
                        data-xy="xo:31px,24px,18px,11px;y:m;yo:116px,96px,22px,13px;"
                        data-text="w:normal;s:20,16,12,7;l:0,20,15,9;"
                        data-dim="w:170px,155px,155px,95px;h:22px,18px,20px,12px;"
                        data-vbility="t,t,t,f"
                        data-frame_0="x:100%;"
                        data-frame_0_mask="u:t;"
                        data-frame_1="st:1880;sp:1000;"
                        data-frame_1_mask="u:t;"
                        data-frame_999="o:0;st:w;sR:6820;"
                        style="z-index:8;background-color:#fc0012;"
                    > 
                    </rs-layer>
                </rs-slide>
                <rs-slide style="position: absolute;" data-key="rs-3" data-title="Slide" data-thumb="revolution/images/slider-2.jpg' %}" data-in="o:0;" data-out="a:false;">
                    <img src="{% static 'revolution/images/slider-2.jpg' %}" alt="" title="slider03-img2.jpg' %}" width="1920" height="815" class="rev-slidebg tp-rs-img" data-no-retina>
                    
                    <rs-layer
                        id="slider-1-slide-3-layer-0" 
                        data-type="text"
                        data-rsp_ch="on"
                        data-xy="xo:30px,24px,30px,30px;y:m;yo:-85px,-59px,-50px,-23px;"
                        data-text="w:normal;s:84,75,60,45;l:84,75,60,45;fw:500;"
                        data-frame_0="x:175%;o:1;"
                        data-frame_0_mask="u:t;x:-100%;"
                        data-frame_1="e:power3.out;st:1490;sp:1000;sR:1490;"
                        data-frame_1_mask="u:t;"
                        data-frame_999="o:0;st:w;sR:6510;"
                        style="z-index:10;font-family:'Teko';"
                    >Setting Global Standards<br/>in Geology, Environment <br/> and Oil &amp; Gas Solutions
                    </rs-layer><!--

                    --><rs-layer
                        id="slider-1-slide-3-layer-1" 
                        data-type="text"
                        data-rsp_ch="on"
                        data-xy="xo:30px,24px,30px,18px;y:m;yo:-247px,-199px,-160px,-98px;"
                        data-text="w:normal;s:22,20,20,12;l:30,24,24,14;"
                        data-vbility="t,t,t,f"
                        data-frame_0="x:50,41,31,19;"
                        data-frame_1="st:1000;sp:1000;sR:1000;"
                        data-frame_999="o:0;st:w;sR:7000;"
                        style="z-index:9;font-family:'Yantramanav';"
                    >Geotechnics, Survey, and Beyond
                    </rs-layer>

                    <a id="slider-1-slide-1-layer-2" class="rs-layer rev-button rev-btn" href="contact-us" target="_self" data-type="button" data-rsp_ch="on" data-xy="xo:31px,24px,18px,11px;y:m;yo:116px,96px,22px,13px;" data-text="w:normal;s:18;l:60,55,50,45;ls:1px,1px,1px,0px;fw:300;" data-dim="minh:0px,none,none,none;" data-padding="t:4,5,3,4;r:50,42,40,35;l:50,42,40,35;" data-border="bor:0px,25px,0px,0px;" data-frame_0="x:-100%;" data-frame_0_mask="u:t;" data-frame_1="st:2660;sp:1000;sR:2660;" data-frame_1_mask="u:t;" data-frame_999="o:0;st:w;sR:5340;" data-frame_hover="bgc:#fc0012;bor:0px,25px,0px,0px;" style="z-index:13;background-color:#111010;font-family:'Teko';text-transform:uppercase;"><span>Get a quote</span> 
                    </a>

                    <rs-layer
                        id="slider-1-slide-3-layer-6" 
                        data-type="shape"
                        data-rsp_ch="on"
                        data-xy="xo:197px,175px,181px,111px;y:m;yo:-247px,-199px,-160px,-98px;"
                        data-text="w:normal;s:20,16,12,7;l:0,20,15,9;"
                        data-dim="w:170px,155px,155px,95px;h:22px,18px,20px,12px;"
                        data-vbility="t,t,t,f"
                        data-frame_0="x:100%;"
                        data-frame_0_mask="u:t;"
                        data-frame_1="st:1880;sp:1000;"
                        data-frame_1_mask="u:t;"
                        data-frame_999="o:0;st:w;sR:6820;"
                        style="z-index:8;background-color:#fc0012;"
                    > 
                    </rs-layer>
                </rs-slide>
            </rs-slides>
            <rs-static-layers>
                
            </rs-static-layers>
        </rs-module>
    </rs-module-wrap>
    <!-- END REVOLUTION SLIDER -->
</div>

templates/include/navbar.html
{% load static %}

{% url "main:home" as home %}
{% url "main:about_us" as about_us %}
{% url "main:service_detail" object.id as service_detail %}
{% url "main:our_service" as our_service %}
{% url "main:contact_us" as contact_us %}
{% url "main:team_member" as team_member %}

<div class="pre-header">
    <div class="container-fluid">
        <div class="d-flex justify-content-between align-items-center">
            <div class="pbmit-pre-header-left">
                <ul class="pbmit-contact-info">
                    <li><i class="pbmit-base-icon-phone"></i> Call (+255) 756 844 154</li>
                    <li><i class="pbmit-base-icon-mail-alt"></i> <a href="javascript:void(0);">info@savijo.co.tz</a></li>
                    <li><i class="pbmit-base-icon-pin"></i>Kibugumo Near Kibugumo Dispensary at Efatha Street</li>
                </ul>
            </div>
            <div class="pbmit-pre-header-right">
                <ul class="pbmit-social-links">
                    <li class="pbmit-social-li pbmit-social-facebook">
                        <a href="#" target="_blank">
                            <span><i class="pbmit-base-icon-facebook-squared"></i></span>
                        </a>
                    </li>
                    <li class="pbmit-social-li pbmit-social-twitter">
                        <a href="#" target="_blank">
                            <span><i class="pbmit-base-icon-twitter"></i></span>
                        </a>
                    </li>
                    <li class="pbmit-social-li pbmit-social-instagram">
                        <a href="#" target="_blank">
                            <span><i class="pbmit-base-icon-instagram"></i></span>
                        </a>
                    </li>
                    {% comment %} <li class="pbmit-social-li pbmit-social-youtube">
                        <a href="#" target="_blank">
                            <span><i class="pbmit-base-icon-youtube-play"></i></span>
                        </a>
                    </li> {% endcomment %}
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="site-header-menu" style="background-color: white;">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="d-flex align-items-center justify-content-between">
                    <div class="site-branding">
                        <span class="site-title">
                            <a href="{% url 'main:home' %}">
                                <img class="logo-img" src="{% static 'images/homepage-3/savijo_logo1.jpeg' %}" alt="Savijo Logo">
                            </a>
                        </span>
                    </div>
                    <div class="site-navigations">
                        <nav class="main-menu navbar-expand-xl navbar-light">
                            <div class="navbar-header">
                                <!-- Toggle Button --> 
                                <button class="navbar-toggler" type="button">
                                    <i class="pbmit-base-icon-menu-1"></i>
                                </button>
                            </div>
                            <div class="pbmit-mobile-menu-bg"></div>
                            <div class="collapse navbar-collapse clearfix show" id="pbmit-menu">
                                <div class="pbmit-menu-wrap">
                                    <span class="closepanel">
                                        <i class="pbmit-base-icon-cancel"></i>
                                    </span>
                                    <ul class="navigation clearfix">
                                        <li class="{% if request.path == home or request.path == service_detail %}active{% endif %}">
                                            <a href="{{home}}">Home</a>
                                        </li>

                                        <li class="{% if request.path == about_us %}active{% endif %}">
                                            <a href="{{about_us}}">About Us</a>
                                        </li>

                                        <li class="dropdown {% if request.path == our_service %}active{% endif %}">
                                            <a href="{{our_service}}">Our Service</a>
                                            <ul>

                                                {% for service in services %}
                                                <li><a href="{% url 'main:service_detail' service.id %}">{{service.title}}</a></li>
                                                {% endfor %}
                                                
                                            </ul>
                                        </li>

                                        <li class="{% if request.path == contact_us %}active{% endif %}">
                                            <a href="{{contact_us}}">Contact Us</a>
                                        </li>
                                        
                                        <li class="{% if request.path == team_member %}active{% endif %}">
                                            <a href="{{team_member}}">Team</a>
                                        </li>
                                        
                                    </ul>
                                </div>
                            </div>
                        </nav>
                    </div>
                    <div class="pbmit-right-side">
                        
                        <a href="{{contact_us}}" class="pbmit-btn">
                            <span>Get a quote</span>
                        </a>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/main/service_detail.html
{% extends "master/master.html" %}
{% load static %}

{% block title_bar %}

<!-- Title Bar -->
<div class="pbmit-title-bar-wrapper" style="z-index: -1000;"> <!-- pbmit-title-bar-wrapper -->
    <div class="container">
        <div class="pbmit-title-bar-content">
            <div class="pbmit-title-bar-content-inner">
                <div class="pbmit-tbar">
                    <div class="pbmit-tbar-inner container">
                        <h1 class="pbmit-tbar-title">SERVICE - {{object.title}}</h1>
                    </div>
                </div>
                <div class="pbmit-breadcrumb">
                    <div class="pbmit-breadcrumb-inner">
                        <span><a title="" href="#" class="home"><span>SAVIJO</span></a></span>
                        <span class="sep">
                            <i class="pbmit-base-icon-angle-double-right"></i>
                        </span>
                        <span><span class="post-root post post-post current-item">SERVICE DETAILS</span></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Title Bar End-->

{% endblock title_bar %}


{% block content %}

<!-- service Details --> 
<section class="service-details-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 service-left-col order-2 order-lg-1">
                <aside class="service-sidebar">
                    <aside class="widget post-list">
                        <div class="all-post-list">
                            <h2 class="widget-title">SAVIJO SERVICES</h2>
                            <ul>
                                {% for service in service_list %}
                                <li class="{% if service.id == object.id %}post-active{% endif %}"><a href="{% url "main:service_detail" service.id %}">{{service.title}}</a></li>
                                {% endfor %}

                            </ul>
                        </div>
                    </aside>
                    
                </aside>
            </div>
            <div class="col-lg-9 service-right-col order-1">
                <div class="pbmit-service-single">
                    <img src="{% static 'images/homepage-1/service/service-new-01.jpg' %}" class="img-fluid w-100" alt="">
                </div>
                <div class="service-details">
                    <div class="pbmit-service-contant">
                        <h3 class="pbmit-title text-uppercase">{{object.title}} Service</h3>
                        {{object.description|safe}}
                    </div>
                    
                </div>
            </div>
        </div>
    </div>
</section>
<!-- service Details End -->

{% endblock content %}

templates/main/services.html
{% extends "master/master.html" %}
{% load static %}

{% block title_bar %}

<!-- Title Bar -->
<div class="pbmit-title-bar-wrapper" style="z-index: -1000;"> <!-- pbmit-title-bar-wrapper -->
    <div class="container">
        <div class="pbmit-title-bar-content">
            <div class="pbmit-title-bar-content-inner">
                <div class="pbmit-tbar">
                    <div class="pbmit-tbar-inner container">
                        <h1 class="pbmit-tbar-title">OUR SERVICES</h1>
                    </div>
                </div>
                <div class="pbmit-breadcrumb">
                    <div class="pbmit-breadcrumb-inner">
                        <span><a title="" href="javascript:void(0);" class="home"><span>SAVIJO</span></a></span>
                        <span class="sep">
                            <i class="pbmit-base-icon-angle-double-right"></i>
                        </span>
                        <span><span class="post-root post post-post current-item">ABOUT US</span></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Title Bar End-->

{% endblock title_bar %}


{% block content %}

<!-- service -->
<section class="service-section">
    <div class="container">
        <div class="row">

            {% for object in service_list %}
            <div class="col-md-6 col-xl-4">
                <article class="pbmit-service-style-1">
                    <div class="pbminfotech-post-item">
                        <div class="pbmit-service-img-wrapper">
                            <div class="pbmit-featured-wrapper">
                                <img src="{% static 'images/homepage-1/service/service-new-01.jpg' %}" class="img-fluid" alt="">
                            </div>
                        </div>
                        <div class="pbminfotech-box-content">
                            <div class="pbminfotech-box-content-inner">
                                <div class="d-flex justify-content-between align-items-center">
                                    <h3 class="pbmit-service-title">
                                        <a href="{% url 'main:service_detail' object.id %}">{{object.title}}</a>
                                    </h3>
                                </div>
                                <div class="pbmit-service-content">
                                </div>
                                <div class="pbmit-service-btn">
                                    <a class="btn-arrow" href="{% url 'main:service_detail' object.id %}"><span>View More</span></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
            {% endfor %}
            
        </div>
    </div>
</section>
<!-- service End -->

{% endblock content %}